#!/bin/bash
# Run migrations to update db
python manage.py makemigrations && python manage.py migrate

if [ $# == 0 ]; then
    cmd="python manage.py test"
    echo running all tests
    sleep 2
    ${cmd}
elif [ $1 == 'unit' ]; then
    cmd="python manage.py test -v 2 lists accounts.tests.test_models"
    echo Running unit tests...
    sleep 2
    ${cmd}
elif [ $1 == 'functional' ]; then
    cmd="python manage.py test functional_tests"
    echo running functional tests..
    sleep 2
    ${cmd}
elif [ $1 != 'unit' ] || [ $1 != 'functional' ]; then
    echo invalid arguments
fi

