name: Run unit tests
run-name: Unit tests runner
on: [push]
jobs:
  run-unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./runtests unit
          echo 'Unit tests completed'
