name: Run unit tests
run-name: Unit tests runner
on: [push]
jobs:
  run-unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
      - name: Install Django
        run: pip install -r requirements.txt
      - name: Run Unit Tests
        run:  ./runtests unit
